/**:
  ros__parameters:
    map_frame: "map"
    base_frame: "base"
    loop_pub_hz: 0.1
    loop_update_hz: 2.0
    loop_pub_delayed_time: 30.0
    vis_hz: 1.0

    keyframe:
      keyframe_threshold: 1.5
      num_submap_keyframes: 10
      enable_submap_matching: true

    loop:
      verbose: true
      loop_detection_radius: 10.0
      loop_detection_timediff_threshold: 90.0

    voxel_resolution: 0.3
    save_voxel_resolution: 0.3

    local_reg:
      num_threads: 8
      correspondences_number: 20
      max_num_iter: 32
      scale_factor_for_corr_dist: 5.0
      overlap_threshold: 75.0 # Unit: %. The higher, the more conservative the decision becomes

    global_reg:
      enable: true

    result:
      save_map_pcd: true
      save_map_bag: true
      save_in_kitti_format: true
      seq_name: "sequence"
